### ISSUE TITLE
Not working with Magento 1.9.3.2

### ISSUE THREAD

**Issue by oviliz** [hartmut-ltd/magento-php7-totals-fix#1]
Apparently, your code doesn't work with (mine) Magento 1.9.3.2 as it doesn't avoid wrong cart total amount. Instead this extension was fine, https://github.com/Inchoo/Inchoo_PHP7

**Comment by kkrieger85** [comment]
Works for me very well:

M 1.9.3.6
PHP 7.0.22

**Comment by fabolousfrances** [comment]
works for me very well 👍 

Magento CE : 1.9.3.7
PHP : 7.1.7

**Comment by hartmut-co-uk** [comment]
Closing the issue, the repo is going to be deprecated in favor of the official PHP 7.2 patches for Magento 1.

**Comment by oviliz** [comment]
Thanks for your help @hartmut-co-uk
