### ISSUE TITLE
Fix not working correctly.

### ISSUE THREAD

**Issue by BSHoneyBees** [hartmut-ltd/magento-php7-totals-fix#4]
Hello, installed this fix as suddenly all my totals were incorrect. It would give a grand total without the tax. Now with this fix installed it is giving the total too high as it is adding the tax again at the end.

Subtotal (Excl. Tax)	£37.95 (not correct)
Subtotal (Incl. Tax)	£37.95
Shipping Excl. Tax (Economy Hermes (1-5 Days))	£6.53 (not correct)
Shipping Incl. Tax (Economy Hermes (1-5 Days))	£6.53
Grand Total Excl. Tax	£44.48
Tax	£7.42
Grand Total Incl. Tax	£51.90

total should be £44.48

I set my prices including tax for both shipping & products.

Dan

**Comment by BSHoneyBees** [comment]
Resolved the issue by installing the following https://github.com/Inchoo/Inchoo_PHP7 as per previous post. Headache avoided!

**Comment by hartmut-co-uk** [comment]
Closing the issue, the repo is going to be _deprecated_ in favor of the official PHP 7.2 patches for Magento 1.
