### ISSUE TITLE
Obsolete repo

### ISSUE THREAD

**Issue by snez** [hartmut-ltd/magento-php7-totals-fix#5]
This repository should be depreciated in favour of the new official PHP7.2 patches. The official patches seem to fix all issues.

**Comment by hartmut-co-uk** [comment]
Hi @snez, many thanks for the notice! 
I haven't been working with/on a magento system for quite some time now - so I'm not up to date in any sense.
Would you be able to provide links to the patches you mentioned? 
So I can change the repository description & README to add a clear warning and references.

**Comment by hartmut-co-uk** [comment]
Found everything. 
Thanks again for pointing out!
